<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
<!--        <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>-->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DSharpPlus" />
        <PackageReference Include="DSharpPlus.SlashCommands" />
        <PackageReference Include="System.Threading.RateLimiting" />
    </ItemGroup>

</Project>
