<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
        <NoWarn>
            $(NoWarn);
            MA0036; <!--Make class static-->
        </NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNet.Security.OAuth.Discord" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\PaperMalKing.Database.CompiledModels\PaperMalKing.Database.CompiledModels.csproj" />
        <ProjectReference Include="..\PaperMalKing.Database.Migrations\PaperMalKing.Database.Migrations.csproj" />
        <ProjectReference Include="..\PaperMalKing.Startup\PaperMalKing.Startup.csproj" />
        <ProjectReference Include="..\PaperMalKing.UpdatesProviders.Base\PaperMalKing.UpdatesProviders.Base.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="$(SolutionDir)\tantei.service">
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Include="$(SolutionDir)\LICENSE.md">
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="template.appsettings.Production.json" CopyToPublishDirectory="Always">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="appsettings.json" CopyToPublishDirectory="Always">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="appsettings.Production.json" CopyToPublishDirectory="Never">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="appsettings.Staging.json" CopyToPublishDirectory="Never">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
        <Content Update="neko.json" CopyToPublishDirectory="Never">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

</Project>
