version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/PaperMalKing/ClientApp"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"