<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <PropertyGroup>
    <EntityFrameworkCoreVersion>10.0.3</EntityFrameworkCoreVersion>
    <GraphQLClientVersion>6.1.0</GraphQLClientVersion>
    <DSharpPlusVersion>4.5.1</DSharpPlusVersion>
    <CommunityTookitVersion>8.4.0</CommunityTookitVersion>
    <VisualStudioThreadingVersion>17.14.15</VisualStudioThreadingVersion>

    <VerifyVersion>31.13.2</VerifyVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Logging -->
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Telemetry.Abstractions" Version="10.3.0" />

    <!-- Discord -->
    <PackageVersion Include="DSharpPlus" Version="$(DSharpPlusVersion)" />
    <PackageVersion Include="DSharpPlus.SlashCommands" Version="$(DSharpPlusVersion)" />

    <!-- GraphQl -->
    <PackageVersion Include="GraphQL.Client" Version="$(GraphQLClientVersion)" />
    <PackageVersion Include="GraphQL.Client.Abstractions" Version="$(GraphQLClientVersion)" />
    <PackageVersion Include="GraphQL.Primitives" Version="$(GraphQLClientVersion)" />
    <PackageVersion Include="GraphQL.Client.Serializer.SystemTextJson" Version="$(GraphQLClientVersion)" />

    <!-- EF Core -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Abstractions" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(EntityFrameworkCoreVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="EntityFrameworkCore.Exceptions.Sqlite" Version="8.1.3" />

    <!-- Hosting -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />

    <!-- DI -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />

    <!-- Configuration -->
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.3" />

    <!-- Resilience -->
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.3" />

    <!-- Web -->
    <PackageVersion Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.3" />

    <!-- Misc -->
    <PackageVersion Include="CommunityToolkit.Diagnostics" Version="$(CommunityTookitVersion)" />
    <PackageVersion Include="Humanizer.Core" Version="3.0.1" />
    <PackageVersion Include="AngleSharp" Version="1.4.0" />
    <PackageVersion Include="JikanDotNet" Version="2.10.1" />
    <PackageVersion Include="System.Threading.RateLimiting" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.EnumStrings" Version="8.0.0-rc.2.23510.2" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading" Version="$(VisualStudioThreadingVersion)" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <GlobalPackageReference Include="GitVersion.MsBuild" Version="6.6.0">
        <PrivateAssets>All</PrivateAssets>
    </GlobalPackageReference>
      
    <!-- Benchmarking -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />  

    <!-- Analyzers-->
    <GlobalPackageReference Include="Meziantou.Analyzer" Version="3.0.15">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.19.0.132793">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="Microsoft.Extensions.ExtraAnalyzers" Version="8.0.0-rc.2.23510.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="AsyncFixer" Version="2.1.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="$(VisualStudioThreadingVersion)">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.15.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.8.2-beta.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="ErrorProne.NET.Structs" Version="0.6.1-beta.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.0.0-1.25277.114">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
      
    <!-- Testing -->
    <PackageVersion Include="coverlet.collector" Version="8.0.0" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="3.0.1" />
    <PackageVersion Include="Verify" Version="$(VerifyVersion)" />
    <PackageVersion Include="Verify.TUnit" Version="$(VerifyVersion)" />
    <PackageVersion Include="TUnit" Version="1.17.11" />




    <!-- Implicit -->
    <PackageVersion Include="System.Net.Security" Version="4.3.2" />
    <PackageVersion Include="System.Formats.Asn1" Version="10.0.3" />
    <PackageVersion Include="System.Private.Uri" Version="4.3.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="18.0.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.0.0" />
  </ItemGroup>
</Project>