<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);VSTHRD200;CA1515;EA0004;</NoWarn>
        <IsPublishable>false</IsPublishable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="GitHubActionsTestLogger" />
        <PackageReference Include="Verify" />
        <PackageReference Include="Verify.TUnit" />
        <PackageReference Include="TUnit" />
    </ItemGroup>
</Project>