<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />
    <PropertyGroup>
        <IsTestSupportProject Condition="$(MSBuildProjectName.StartsWith('Tantei.TestSupport.'))">true</IsTestSupportProject>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);VSTHRD200;CA1515;EA0004;AsyncFixer01;</NoWarn>
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsTestSupportProject)' != 'true'">
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsTestSupportProject)' != 'true'">
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="GitHubActionsTestLogger" />
        <PackageReference Include="Verify" />
        <PackageReference Include="Verify.TUnit" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    </ItemGroup>

    <ItemGroup Condition="'$(IsTestSupportProject)' != 'true'">
        <Using Include="Microsoft.Extensions.Time.Testing" />
        <Using Include="Tantei.TestSupport" />
    </ItemGroup>

    <ItemGroup Condition="'$(IsTestSupportProject)' != 'true'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)Tantei.TestSupport.Core\Tantei.TestSupport.Core.csproj" />
    </ItemGroup>
</Project>