<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>
            $(NoWarn);MA0048;MA0197;S1186;RCS1205;RCS1036;RCS1021;CA1861;SA1027;SA1502;SA1505;SA1508;SA1413;IDE0300;S3254;IDE0055;S101;
            EF8001; <!--'RelationalOwnedNavigationBuilderExtensions.ToJson(OwnedNavigationBuilder, string?)' is obsolete: 'ToJson() on owned entities has been obsoleted, please switch to using complex types instead for mapping to JSON. See https://aka.ms/efcore-docs-json-owned-entities for more information, and provide feedback on https://github.com/dotnet/efcore/issues/37290 if the transition causes problems for you.'-->
        </NoWarn>
        <DebugSymbols>false</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <ProjectReference Include="..\PaperMalKing.Database\PaperMalKing.Database.csproj" />
    </ItemGroup>

</Project>
