// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;
using PaperMalKing.Database.Models.AniList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class AniListUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref uint Id(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUserId>k__BackingField")]
        public static extern ref ulong DiscordUserId(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavouritesIdHash>k__BackingField")]
        public static extern ref string FavouritesIdHash(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Features>k__BackingField")]
        public static extern ref AniListUserFeatures Features(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastActivityTimestamp>k__BackingField")]
        public static extern ref long LastActivityTimestamp(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastReviewTimestamp>k__BackingField")]
        public static extern ref long LastReviewTimestamp(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Colors>k__BackingField")]
        public static extern ref List<CustomUpdateColor> Colors(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUser>k__BackingField")]
        public static extern ref DiscordUser DiscordUser(AniListUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Favourites>k__BackingField")]
        public static extern ref IList<AniListFavourite> Favourites(AniListUser @this);
    }
}
