// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models.MyAnimeList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class BaseMalFavoriteUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref uint Id(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref uint UserId(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoriteType>k__BackingField")]
        public static extern ref MalFavoriteType FavoriteType(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ImageUrl>k__BackingField")]
        public static extern ref string ImageUrl(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NameUrl>k__BackingField")]
        public static extern ref string NameUrl(BaseMalFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<User>k__BackingField")]
        public static extern ref MalUser User(BaseMalFavorite @this);
    }
}
