// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models.MyAnimeList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class BaseMalListFavoriteUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartYear>k__BackingField")]
        public static extern ref ushort StartYear(BaseMalListFavorite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref string Type(BaseMalListFavorite @this);
    }
}
