// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class BotUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref uint UserId(BotUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUser>k__BackingField")]
        public static extern ref DiscordUser DiscordUser(BotUser @this);
    }
}
