// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class CustomUpdateColorUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ColorValue>k__BackingField")]
        public static extern ref int ColorValue(CustomUpdateColor @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdateType>k__BackingField")]
        public static extern ref byte UpdateType(CustomUpdateColor @this);
    }
}
