// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PaperMalKing.Database.CompiledModels
{
    [DbContext(typeof(DatabaseContext))]
    public partial class DatabaseContextModel : RuntimeModel
    {
        static DatabaseContextModel()
        {
            var model = new DatabaseContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DatabaseContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
