// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using PaperMalKing.Database;
using PaperMalKing.Database.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DatabaseContext), typeof(DatabaseContextModel))]
