// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class DiscordUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUserId>k__BackingField")]
        public static extern ref ulong DiscordUserId(DiscordUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BotUserId>k__BackingField")]
        public static extern ref uint BotUserId(DiscordUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BotUser>k__BackingField")]
        public static extern ref BotUser BotUser(DiscordUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Guilds>k__BackingField")]
        public static extern ref IList<DiscordGuild> Guilds(DiscordUser @this);
    }
}
