// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class DiscordGuildUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordGuildId>k__BackingField")]
        public static extern ref ulong DiscordGuildId(DiscordGuild @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PostingChannelId>k__BackingField")]
        public static extern ref ulong PostingChannelId(DiscordGuild @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Users>k__BackingField")]
        public static extern ref IList<DiscordUser> Users(DiscordGuild @this);
    }
}
