// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PaperMalKing.Database.Models.MyAnimeList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MalFavoriteCompanyEntityType
    {
        var runtimeEntityType = model.AddEntityType(
            "PaperMalKing.Database.Models.MyAnimeList.MalFavoriteCompany",
            typeof(MalFavoriteCompany),
            baseEntityType,
            discriminatorProperty: "FavoriteType",
            propertyCount: 0,
            navigationCount: 1,
            foreignKeyCount: 1);

        runtimeEntityType.SetDiscriminatorValueFromProviderValue((byte)5);

        return runtimeEntityType;
    }
}
