// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models.MyAnimeList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class MalFavoriteCharacterUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FromTitleName>k__BackingField")]
        public static extern ref string FromTitleName(MalFavoriteCharacter @this);
    }
}
