// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models;
using PaperMalKing.Database.Models.MyAnimeList;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class MalUserUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref uint UserId(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUserId>k__BackingField")]
        public static extern ref ulong DiscordUserId(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoritesIdHash>k__BackingField")]
        public static extern ref string FavoritesIdHash(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Features>k__BackingField")]
        public static extern ref MalUserFeatures Features(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastAnimeUpdateHash>k__BackingField")]
        public static extern ref string LastAnimeUpdateHash(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastMangaUpdateHash>k__BackingField")]
        public static extern ref string LastMangaUpdateHash(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUpdatedAnimeListTimestamp>k__BackingField")]
        public static extern ref DateTimeOffset LastUpdatedAnimeListTimestamp(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUpdatedMangaListTimestamp>k__BackingField")]
        public static extern ref DateTimeOffset LastUpdatedMangaListTimestamp(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Username>k__BackingField")]
        public static extern ref string Username(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Colors>k__BackingField")]
        public static extern ref List<CustomUpdateColor> Colors(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiscordUser>k__BackingField")]
        public static extern ref DiscordUser DiscordUser(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoriteAnimes>k__BackingField")]
        public static extern ref IList<MalFavoriteAnime> FavoriteAnimes(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoriteCharacters>k__BackingField")]
        public static extern ref IList<MalFavoriteCharacter> FavoriteCharacters(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoriteCompanies>k__BackingField")]
        public static extern ref IList<MalFavoriteCompany> FavoriteCompanies(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoriteMangas>k__BackingField")]
        public static extern ref IList<MalFavoriteManga> FavoriteMangas(MalUser @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavoritePeople>k__BackingField")]
        public static extern ref IList<MalFavoritePerson> FavoritePeople(MalUser @this);
    }
}
