// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PaperMalKing.Database.Models;
using PaperMalKing.Database.Models.Shikimori;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels;

[EntityFrameworkInternal]
public partial class ShikiUserEntityType
{
    public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
    {
        var runtimeEntityType = model.AddEntityType(
            "PaperMalKing.Database.Models.Shikimori.ShikiUser",
            typeof(ShikiUser),
            baseEntityType,
            propertyCount: 5,
            complexPropertyCount: 2,
            navigationCount: 2,
            foreignKeyCount: 1,
            unnamedIndexCount: 2,
            keyCount: 1);

        var id = runtimeEntityType.AddProperty(
            "Id",
            typeof(uint),
            propertyInfo: typeof(ShikiUser).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            afterSaveBehavior: PropertySaveBehavior.Throw,
            sentinel: 0u);

        var discordUserId = runtimeEntityType.AddProperty(
            "DiscordUserId",
            typeof(ulong),
            propertyInfo: typeof(ShikiUser).GetProperty("DiscordUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<DiscordUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0ul);

        var favouritesIdHash = runtimeEntityType.AddProperty(
            "FavouritesIdHash",
            typeof(string),
            propertyInfo: typeof(ShikiUser).GetProperty("FavouritesIdHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<FavouritesIdHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd);
        favouritesIdHash.AddAnnotation("Relational:DefaultValue", "");

        var features = runtimeEntityType.AddProperty(
            "Features",
            typeof(ShikiUserFeatures),
            propertyInfo: typeof(ShikiUser).GetProperty("Features", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<Features>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            valueGenerated: ValueGenerated.OnAdd);
        features.SetSentinelFromProviderValue(0ul);
        features.AddAnnotation("Relational:DefaultValue", ShikiUserFeatures.AnimeList | ShikiUserFeatures.MangaList | ShikiUserFeatures.Favourites | ShikiUserFeatures.Mention | ShikiUserFeatures.Website | ShikiUserFeatures.MediaFormat | ShikiUserFeatures.MediaStatus);

        var lastHistoryEntryId = runtimeEntityType.AddProperty(
            "LastHistoryEntryId",
            typeof(uint),
            propertyInfo: typeof(ShikiUser).GetProperty("LastHistoryEntryId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<LastHistoryEntryId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0u);

        AchievementsComplexProperty.Create(runtimeEntityType);
        ColorsComplexProperty.Create(runtimeEntityType);
        var key = runtimeEntityType.AddKey(
            new[] { id });
        runtimeEntityType.SetPrimaryKey(key);

        var index = runtimeEntityType.AddIndex(
            new[] { discordUserId },
            unique: true);

        var index0 = runtimeEntityType.AddIndex(
            new[] { features });

        return runtimeEntityType;
    }

    public static class AchievementsComplexProperty
    {
        public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
        {
            var complexProperty = declaringType.AddComplexProperty("Achievements",
                typeof(List<ShikiDbAchievement>),
                "PaperMalKing.Database.Models.Shikimori.ShikiUser.Achievements#ShikiDbAchievement",
                typeof(ShikiDbAchievement),
                propertyInfo: typeof(ShikiUser).GetProperty("Achievements", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<Achievements>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                collection: true,
                propertyCount: 2);

            var complexType = complexProperty.ComplexType;
            var level = complexType.AddProperty(
                "Level",
                typeof(byte),
                propertyInfo: typeof(ShikiDbAchievement).GetProperty("Level", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiDbAchievement).GetField("<Level>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);

            var nekoId = complexType.AddProperty(
                "NekoId",
                typeof(string),
                propertyInfo: typeof(ShikiDbAchievement).GetProperty("NekoId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiDbAchievement).GetField("<NekoId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            complexType.AddAnnotation("Relational:ContainerColumnName", "Achievements");
            complexType.AddAnnotation("Relational:FunctionName", null);
            complexType.AddAnnotation("Relational:Schema", null);
            complexType.AddAnnotation("Relational:SqlQuery", null);
            complexType.AddAnnotation("Relational:TableName", "ShikiUsers");
            complexType.AddAnnotation("Relational:ViewName", null);
            complexType.AddAnnotation("Relational:ViewSchema", null);
            return complexProperty;
        }
    }

    public static class ColorsComplexProperty
    {
        public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
        {
            var complexProperty = declaringType.AddComplexProperty("Colors",
                typeof(List<CustomUpdateColor>),
                "PaperMalKing.Database.Models.Shikimori.ShikiUser.Colors#CustomUpdateColor",
                typeof(CustomUpdateColor),
                propertyInfo: typeof(ShikiUser).GetProperty("Colors", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<Colors>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                collection: true,
                propertyCount: 2);

            var complexType = complexProperty.ComplexType;
            var colorValue = complexType.AddProperty(
                "ColorValue",
                typeof(int),
                propertyInfo: typeof(CustomUpdateColor).GetProperty("ColorValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CustomUpdateColor).GetField("<ColorValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var updateType = complexType.AddProperty(
                "UpdateType",
                typeof(byte),
                propertyInfo: typeof(CustomUpdateColor).GetProperty("UpdateType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CustomUpdateColor).GetField("<UpdateType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);

            complexType.AddAnnotation("Relational:ContainerColumnName", "Colors");
            complexType.AddAnnotation("Relational:FunctionName", null);
            complexType.AddAnnotation("Relational:Schema", null);
            complexType.AddAnnotation("Relational:SqlQuery", null);
            complexType.AddAnnotation("Relational:TableName", "ShikiUsers");
            complexType.AddAnnotation("Relational:ViewName", null);
            complexType.AddAnnotation("Relational:ViewSchema", null);
            return complexProperty;
        }
    }

    public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
    {
        var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DiscordUserId") },
            principalEntityType.FindKey(new[] { principalEntityType.FindProperty("DiscordUserId") }),
            principalEntityType,
            deleteBehavior: DeleteBehavior.Cascade,
            unique: true,
            required: true);

        var discordUser = declaringEntityType.AddNavigation("DiscordUser",
            runtimeForeignKey,
            onDependent: true,
            typeof(DiscordUser),
            propertyInfo: typeof(ShikiUser).GetProperty("DiscordUser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ShikiUser).GetField("<DiscordUser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

        return runtimeForeignKey;
    }

    public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
    {
        runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
        runtimeEntityType.AddAnnotation("Relational:Schema", null);
        runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
        runtimeEntityType.AddAnnotation("Relational:TableName", "ShikiUsers");
        runtimeEntityType.AddAnnotation("Relational:ViewName", null);
        runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

        Customize(runtimeEntityType);
    }

    static partial void Customize(RuntimeEntityType runtimeEntityType);
}
