// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using PaperMalKing.Database.Models.Shikimori;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    public static class ShikiFavouriteUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref uint Id(ShikiFavourite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FavType>k__BackingField")]
        public static extern ref string FavType(ShikiFavourite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref uint UserId(ShikiFavourite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(ShikiFavourite @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<User>k__BackingField")]
        public static extern ref ShikiUser User(ShikiFavourite @this);
    }
}
