// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using PaperMalKing.Database.Models.Shikimori;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ShikiDbAchievementEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "PaperMalKing.Database.Models.Shikimori.ShikiDbAchievement",
                typeof(ShikiDbAchievement),
                baseEntityType,
                propertyCount: 4,
                foreignKeyCount: 1,
                keyCount: 1);

            var shikiUserId = runtimeEntityType.AddProperty(
                "ShikiUserId",
                typeof(uint),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0u);
            shikiUserId.SetAccessors(
                uint (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<uint>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<uint>(0) == 0U ? entry.ReadTemporaryValue<uint>(0) : entry.ReadShadowValue<uint>(0))),
                uint (InternalEntityEntry entry) => entry.ReadShadowValue<uint>(0),
                uint (InternalEntityEntry entry) => entry.ReadOriginalValue<uint>(shikiUserId, 0),
                uint (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<uint>(shikiUserId, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            shikiUserId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            shikiUserId.TypeMapping = UIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            shikiUserId.SetCurrentValueComparer(new EntryCurrentValueComparer<uint>(shikiUserId));

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetAccessors(
                int (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<int>(1) : (entry.FlaggedAsTemporary(1) && entry.ReadShadowValue<int>(1) == 0 ? entry.ReadTemporaryValue<int>(1) : entry.ReadShadowValue<int>(1))),
                int (InternalEntityEntry entry) => entry.ReadShadowValue<int>(1),
                int (InternalEntityEntry entry) => entry.ReadOriginalValue<int>(id, 1),
                int (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<int>(id, 1),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            id.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var level = runtimeEntityType.AddProperty(
                "Level",
                typeof(byte),
                propertyInfo: typeof(ShikiDbAchievement).GetProperty("Level", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiDbAchievement).GetField("<Level>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (byte)0);
            level.SetGetter(
                byte (ShikiDbAchievement entity) => ShikiDbAchievementUnsafeAccessors.Level(entity),
                bool (ShikiDbAchievement entity) => ShikiDbAchievementUnsafeAccessors.Level(entity) == 0,
                byte (ShikiDbAchievement instance) => ShikiDbAchievementUnsafeAccessors.Level(instance),
                bool (ShikiDbAchievement instance) => ShikiDbAchievementUnsafeAccessors.Level(instance) == 0);
            level.SetSetter(
                (ShikiDbAchievement entity, byte value) => ShikiDbAchievementUnsafeAccessors.Level(entity) = value);
            level.SetMaterializationSetter(
                (ShikiDbAchievement entity, byte value) => ShikiDbAchievementUnsafeAccessors.Level(entity) = value);
            level.SetAccessors(
                byte (InternalEntityEntry entry) => ShikiDbAchievementUnsafeAccessors.Level(((ShikiDbAchievement)(entry.Entity))),
                byte (InternalEntityEntry entry) => ShikiDbAchievementUnsafeAccessors.Level(((ShikiDbAchievement)(entry.Entity))),
                byte (InternalEntityEntry entry) => entry.ReadOriginalValue<byte>(level, 2),
                byte (InternalEntityEntry entry) => entry.GetCurrentValue<byte>(level),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            level.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            level.TypeMapping = ByteTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte>(
                    bool (byte v1, byte v2) => v1 == v2,
                    int (byte v) => ((int)(v)),
                    byte (byte v) => v),
                keyComparer: new ValueComparer<byte>(
                    bool (byte v1, byte v2) => v1 == v2,
                    int (byte v) => ((int)(v)),
                    byte (byte v) => v),
                providerValueComparer: new ValueComparer<byte>(
                    bool (byte v1, byte v2) => v1 == v2,
                    int (byte v) => ((int)(v)),
                    byte (byte v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var nekoId = runtimeEntityType.AddProperty(
                "NekoId",
                typeof(string),
                propertyInfo: typeof(ShikiDbAchievement).GetProperty("NekoId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiDbAchievement).GetField("<NekoId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            nekoId.SetGetter(
                string (ShikiDbAchievement entity) => ShikiDbAchievementUnsafeAccessors.NekoId(entity),
                bool (ShikiDbAchievement entity) => ShikiDbAchievementUnsafeAccessors.NekoId(entity) == null,
                string (ShikiDbAchievement instance) => ShikiDbAchievementUnsafeAccessors.NekoId(instance),
                bool (ShikiDbAchievement instance) => ShikiDbAchievementUnsafeAccessors.NekoId(instance) == null);
            nekoId.SetSetter(
                (ShikiDbAchievement entity, string value) => ShikiDbAchievementUnsafeAccessors.NekoId(entity) = value);
            nekoId.SetMaterializationSetter(
                (ShikiDbAchievement entity, string value) => ShikiDbAchievementUnsafeAccessors.NekoId(entity) = value);
            nekoId.SetAccessors(
                string (InternalEntityEntry entry) => ShikiDbAchievementUnsafeAccessors.NekoId(((ShikiDbAchievement)(entry.Entity))),
                string (InternalEntityEntry entry) => ShikiDbAchievementUnsafeAccessors.NekoId(((ShikiDbAchievement)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(nekoId, 3),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(nekoId),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            nekoId.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            nekoId.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { shikiUserId, id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ShikiUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var achievements = principalEntityType.AddNavigation("Achievements",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<ShikiDbAchievement>),
                propertyInfo: typeof(ShikiUser).GetProperty("Achievements", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<Achievements>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            achievements.SetGetter(
                List<ShikiDbAchievement> (ShikiUser entity) => ShikiUserUnsafeAccessors.Achievements(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.Achievements(entity) == null,
                List<ShikiDbAchievement> (ShikiUser instance) => ShikiUserUnsafeAccessors.Achievements(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.Achievements(instance) == null);
            achievements.SetSetter(
                (ShikiUser entity, List<ShikiDbAchievement> value) => ShikiUserUnsafeAccessors.Achievements(entity) = value);
            achievements.SetMaterializationSetter(
                (ShikiUser entity, List<ShikiDbAchievement> value) => ShikiUserUnsafeAccessors.Achievements(entity) = value);
            achievements.SetAccessors(
                List<ShikiDbAchievement> (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.Achievements(((ShikiUser)(entry.Entity))),
                List<ShikiDbAchievement> (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.Achievements(((ShikiUser)(entry.Entity))),
                null,
                List<ShikiDbAchievement> (InternalEntityEntry entry) => entry.GetCurrentValue<List<ShikiDbAchievement>>(achievements),
                null);
            achievements.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            achievements.SetCollectionAccessor<ShikiUser, List<ShikiDbAchievement>, ShikiDbAchievement>(
                List<ShikiDbAchievement> (ShikiUser entity) => ShikiUserUnsafeAccessors.Achievements(entity),
                (ShikiUser entity, List<ShikiDbAchievement> collection) => ShikiUserUnsafeAccessors.Achievements(entity) = ((List<ShikiDbAchievement>)(collection)),
                (ShikiUser entity, List<ShikiDbAchievement> collection) => ShikiUserUnsafeAccessors.Achievements(entity) = ((List<ShikiDbAchievement>)(collection)),
                List<ShikiDbAchievement> (ShikiUser entity, Action<ShikiUser, List<ShikiDbAchievement>> setter) => ClrCollectionAccessorFactory.CreateAndSet<ShikiUser, List<ShikiDbAchievement>, List<ShikiDbAchievement>>(entity, setter),
                List<ShikiDbAchievement> () => new List<ShikiDbAchievement>());
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var shikiUserId = runtimeEntityType.FindProperty("ShikiUserId");
            var id = runtimeEntityType.FindProperty("Id");
            var level = runtimeEntityType.FindProperty("Level");
            var nekoId = runtimeEntityType.FindProperty("NekoId");
            var key = runtimeEntityType.FindKey(new[] { shikiUserId, id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((ShikiDbAchievement)(source.Entity));
                    return ((ISnapshot)(new Snapshot<uint, int, byte, string>(((ValueComparer<uint>)(((IProperty)shikiUserId).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(shikiUserId)), ((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<byte>)(((IProperty)level).GetValueComparer())).Snapshot(source.GetCurrentValue<byte>(level)), (source.GetCurrentValue<string>(nekoId) == null ? null : ((ValueComparer<string>)(((IProperty)nekoId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(nekoId))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<uint, int>(((ValueComparer<uint>)(((IProperty)shikiUserId).GetValueComparer())).Snapshot(default(uint)), ((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<uint, int>(default(uint), default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<uint, int>((source.ContainsKey("ShikiUserId") ? ((uint)(source["ShikiUserId"])) : 0U), (source.ContainsKey("Id") ? ((int)(source["Id"])) : 0)))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<uint, int>(default(uint), default(int)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((ShikiDbAchievement)(source.Entity));
                    return ((ISnapshot)(new Snapshot<uint, int>(((ValueComparer<uint>)(((IProperty)shikiUserId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<uint>(shikiUserId)), ((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 4,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2);
            runtimeEntityType.AddAnnotation("Relational:ContainerColumnName", "Achievements");
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ShikiUsers");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
