// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaperMalKing.Database.Models;
using PaperMalKing.Database.Models.Shikimori;

#pragma warning disable 219, 612, 618
#nullable disable

namespace PaperMalKing.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ShikiUserEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "PaperMalKing.Database.Models.Shikimori.ShikiUser",
                typeof(ShikiUser),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 4,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(uint),
                propertyInfo: typeof(ShikiUser).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0u);
            id.SetGetter(
                uint (ShikiUser entity) => ShikiUserUnsafeAccessors.Id(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.Id(entity) == 0U,
                uint (ShikiUser instance) => ShikiUserUnsafeAccessors.Id(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.Id(instance) == 0U);
            id.SetSetter(
                (ShikiUser entity, uint value) => ShikiUserUnsafeAccessors.Id(entity) = value);
            id.SetMaterializationSetter(
                (ShikiUser entity, uint value) => ShikiUserUnsafeAccessors.Id(entity) = value);
            id.SetAccessors(
                uint (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.Id(((ShikiUser)(entry.Entity))),
                uint (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.Id(((ShikiUser)(entry.Entity))),
                uint (InternalEntityEntry entry) => entry.ReadOriginalValue<uint>(id, 0),
                uint (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<uint>(id, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = UIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<uint>(id));

            var discordUserId = runtimeEntityType.AddProperty(
                "DiscordUserId",
                typeof(ulong),
                propertyInfo: typeof(ShikiUser).GetProperty("DiscordUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<DiscordUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0ul);
            discordUserId.SetGetter(
                ulong (ShikiUser entity) => ShikiUserUnsafeAccessors.DiscordUserId(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.DiscordUserId(entity) == 0UL,
                ulong (ShikiUser instance) => ShikiUserUnsafeAccessors.DiscordUserId(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.DiscordUserId(instance) == 0UL);
            discordUserId.SetSetter(
                (ShikiUser entity, ulong value) => ShikiUserUnsafeAccessors.DiscordUserId(entity) = value);
            discordUserId.SetMaterializationSetter(
                (ShikiUser entity, ulong value) => ShikiUserUnsafeAccessors.DiscordUserId(entity) = value);
            discordUserId.SetAccessors(
                ulong (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<ulong>(0) : (entry.FlaggedAsTemporary(1) && ShikiUserUnsafeAccessors.DiscordUserId(((ShikiUser)(entry.Entity))) == 0UL ? entry.ReadTemporaryValue<ulong>(0) : ShikiUserUnsafeAccessors.DiscordUserId(((ShikiUser)(entry.Entity))))),
                ulong (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.DiscordUserId(((ShikiUser)(entry.Entity))),
                ulong (InternalEntityEntry entry) => entry.ReadOriginalValue<ulong>(discordUserId, 1),
                ulong (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<ulong>(discordUserId, 1),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            discordUserId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 0);
            discordUserId.TypeMapping = SqliteULongTypeMapping.Default;
            discordUserId.SetCurrentValueComparer(new EntryCurrentValueComparer<ulong>(discordUserId));

            var favouritesIdHash = runtimeEntityType.AddProperty(
                "FavouritesIdHash",
                typeof(string),
                propertyInfo: typeof(ShikiUser).GetProperty("FavouritesIdHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<FavouritesIdHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            favouritesIdHash.SetGetter(
                string (ShikiUser entity) => ShikiUserUnsafeAccessors.FavouritesIdHash(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.FavouritesIdHash(entity) == null,
                string (ShikiUser instance) => ShikiUserUnsafeAccessors.FavouritesIdHash(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.FavouritesIdHash(instance) == null);
            favouritesIdHash.SetSetter(
                (ShikiUser entity, string value) => ShikiUserUnsafeAccessors.FavouritesIdHash(entity) = value);
            favouritesIdHash.SetMaterializationSetter(
                (ShikiUser entity, string value) => ShikiUserUnsafeAccessors.FavouritesIdHash(entity) = value);
            favouritesIdHash.SetAccessors(
                string (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(2) ? entry.ReadStoreGeneratedValue<string>(1) : (entry.FlaggedAsTemporary(2) && ShikiUserUnsafeAccessors.FavouritesIdHash(((ShikiUser)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(1) : ShikiUserUnsafeAccessors.FavouritesIdHash(((ShikiUser)(entry.Entity))))),
                string (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.FavouritesIdHash(((ShikiUser)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(favouritesIdHash, 2),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(favouritesIdHash),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            favouritesIdHash.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: 1);
            favouritesIdHash.TypeMapping = SqliteStringTypeMapping.Default;
            favouritesIdHash.AddAnnotation("Relational:DefaultValue", "");

            var features = runtimeEntityType.AddProperty(
                "Features",
                typeof(ShikiUserFeatures),
                propertyInfo: typeof(ShikiUser).GetProperty("Features", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<Features>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            features.SetGetter(
                ShikiUserFeatures (ShikiUser entity) => ShikiUserUnsafeAccessors.Features(entity),
                bool (ShikiUser entity) => object.Equals(((object)(ShikiUserUnsafeAccessors.Features(entity))), ((object)(ShikiUserFeatures.None))),
                ShikiUserFeatures (ShikiUser instance) => ShikiUserUnsafeAccessors.Features(instance),
                bool (ShikiUser instance) => object.Equals(((object)(ShikiUserUnsafeAccessors.Features(instance))), ((object)(ShikiUserFeatures.None))));
            features.SetSetter(
                (ShikiUser entity, ShikiUserFeatures value) => ShikiUserUnsafeAccessors.Features(entity) = value);
            features.SetMaterializationSetter(
                (ShikiUser entity, ShikiUserFeatures value) => ShikiUserUnsafeAccessors.Features(entity) = value);
            features.SetAccessors(
                ShikiUserFeatures (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(3) ? entry.ReadStoreGeneratedValue<ShikiUserFeatures>(2) : (entry.FlaggedAsTemporary(3) && object.Equals(((object)(ShikiUserUnsafeAccessors.Features(((ShikiUser)(entry.Entity))))), ((object)(ShikiUserFeatures.None))) ? entry.ReadTemporaryValue<ShikiUserFeatures>(2) : ShikiUserUnsafeAccessors.Features(((ShikiUser)(entry.Entity))))),
                ShikiUserFeatures (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.Features(((ShikiUser)(entry.Entity))),
                ShikiUserFeatures (InternalEntityEntry entry) => entry.ReadOriginalValue<ShikiUserFeatures>(features, 3),
                ShikiUserFeatures (InternalEntityEntry entry) => entry.GetCurrentValue<ShikiUserFeatures>(features),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            features.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: 2);
            features.TypeMapping = SqliteULongTypeMapping.Default.Clone(
                comparer: new ValueComparer<ShikiUserFeatures>(
                    bool (ShikiUserFeatures v1, ShikiUserFeatures v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (ShikiUserFeatures v) => ((object)v).GetHashCode(),
                    ShikiUserFeatures (ShikiUserFeatures v) => v),
                keyComparer: new ValueComparer<ShikiUserFeatures>(
                    bool (ShikiUserFeatures v1, ShikiUserFeatures v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (ShikiUserFeatures v) => ((object)v).GetHashCode(),
                    ShikiUserFeatures (ShikiUserFeatures v) => v),
                providerValueComparer: new ValueComparer<ulong>(
                    bool (ulong v1, ulong v2) => v1 == v2,
                    int (ulong v) => ((object)v).GetHashCode(),
                    ulong (ulong v) => v),
                converter: new ValueConverter<ShikiUserFeatures, ulong>(
                    ulong (ShikiUserFeatures value) => ((ulong)(value)),
                    ShikiUserFeatures (ulong value) => ((ShikiUserFeatures)(value))),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ShikiUserFeatures, ulong>(
                    JsonUInt64ReaderWriter.Instance,
                    new ValueConverter<ShikiUserFeatures, ulong>(
                        ulong (ShikiUserFeatures value) => ((ulong)(value)),
                        ShikiUserFeatures (ulong value) => ((ShikiUserFeatures)(value)))));
            features.SetSentinelFromProviderValue(0ul);
            features.AddAnnotation("Relational:DefaultValue", ShikiUserFeatures.AnimeList | ShikiUserFeatures.MangaList | ShikiUserFeatures.Favourites | ShikiUserFeatures.Mention | ShikiUserFeatures.Website | ShikiUserFeatures.MediaFormat | ShikiUserFeatures.MediaStatus);

            var lastHistoryEntryId = runtimeEntityType.AddProperty(
                "LastHistoryEntryId",
                typeof(uint),
                propertyInfo: typeof(ShikiUser).GetProperty("LastHistoryEntryId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<LastHistoryEntryId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);
            lastHistoryEntryId.SetGetter(
                uint (ShikiUser entity) => ShikiUserUnsafeAccessors.LastHistoryEntryId(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.LastHistoryEntryId(entity) == 0U,
                uint (ShikiUser instance) => ShikiUserUnsafeAccessors.LastHistoryEntryId(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.LastHistoryEntryId(instance) == 0U);
            lastHistoryEntryId.SetSetter(
                (ShikiUser entity, uint value) => ShikiUserUnsafeAccessors.LastHistoryEntryId(entity) = value);
            lastHistoryEntryId.SetMaterializationSetter(
                (ShikiUser entity, uint value) => ShikiUserUnsafeAccessors.LastHistoryEntryId(entity) = value);
            lastHistoryEntryId.SetAccessors(
                uint (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.LastHistoryEntryId(((ShikiUser)(entry.Entity))),
                uint (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.LastHistoryEntryId(((ShikiUser)(entry.Entity))),
                uint (InternalEntityEntry entry) => entry.ReadOriginalValue<uint>(lastHistoryEntryId, 4),
                uint (InternalEntityEntry entry) => entry.GetCurrentValue<uint>(lastHistoryEntryId),
                object (ValueBuffer valueBuffer) => valueBuffer[4]);
            lastHistoryEntryId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            lastHistoryEntryId.TypeMapping = UIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                keyComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                providerValueComparer: new ValueComparer<uint>(
                    bool (uint v1, uint v2) => v1 == v2,
                    int (uint v) => ((int)(v)),
                    uint (uint v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { discordUserId },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { features });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DiscordUserId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("DiscordUserId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true);

            var discordUser = declaringEntityType.AddNavigation("DiscordUser",
                runtimeForeignKey,
                onDependent: true,
                typeof(DiscordUser),
                propertyInfo: typeof(ShikiUser).GetProperty("DiscordUser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShikiUser).GetField("<DiscordUser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            discordUser.SetGetter(
                DiscordUser (ShikiUser entity) => ShikiUserUnsafeAccessors.DiscordUser(entity),
                bool (ShikiUser entity) => ShikiUserUnsafeAccessors.DiscordUser(entity) == null,
                DiscordUser (ShikiUser instance) => ShikiUserUnsafeAccessors.DiscordUser(instance),
                bool (ShikiUser instance) => ShikiUserUnsafeAccessors.DiscordUser(instance) == null);
            discordUser.SetSetter(
                (ShikiUser entity, DiscordUser value) => ShikiUserUnsafeAccessors.DiscordUser(entity) = value);
            discordUser.SetMaterializationSetter(
                (ShikiUser entity, DiscordUser value) => ShikiUserUnsafeAccessors.DiscordUser(entity) = value);
            discordUser.SetAccessors(
                DiscordUser (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.DiscordUser(((ShikiUser)(entry.Entity))),
                DiscordUser (InternalEntityEntry entry) => ShikiUserUnsafeAccessors.DiscordUser(((ShikiUser)(entry.Entity))),
                null,
                DiscordUser (InternalEntityEntry entry) => entry.GetCurrentValue<DiscordUser>(discordUser),
                null);
            discordUser.SetPropertyIndexes(
                index: 2,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 4,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var discordUserId = runtimeEntityType.FindProperty("DiscordUserId");
            var favouritesIdHash = runtimeEntityType.FindProperty("FavouritesIdHash");
            var features = runtimeEntityType.FindProperty("Features");
            var lastHistoryEntryId = runtimeEntityType.FindProperty("LastHistoryEntryId");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<uint>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<uint>(key));
            var achievements = runtimeEntityType.FindNavigation("Achievements");
            var colors = runtimeEntityType.FindNavigation("Colors");
            var discordUser = runtimeEntityType.FindNavigation("DiscordUser");
            var favourites = runtimeEntityType.FindNavigation("Favourites");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((ShikiUser)(source.Entity));
                    return ((ISnapshot)(new Snapshot<uint, ulong, string, ShikiUserFeatures, uint>(((ValueComparer<uint>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(id)), ((ValueComparer<ulong>)(((IProperty)discordUserId).GetValueComparer())).Snapshot(source.GetCurrentValue<ulong>(discordUserId)), (source.GetCurrentValue<string>(favouritesIdHash) == null ? null : ((ValueComparer<string>)(((IProperty)favouritesIdHash).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(favouritesIdHash))), ((ValueComparer<ShikiUserFeatures>)(((IProperty)features).GetValueComparer())).Snapshot(source.GetCurrentValue<ShikiUserFeatures>(features)), ((ValueComparer<uint>)(((IProperty)lastHistoryEntryId).GetValueComparer())).Snapshot(source.GetCurrentValue<uint>(lastHistoryEntryId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<ulong, string, ShikiUserFeatures>(((ValueComparer<ulong>)(((IProperty)discordUserId).GetValueComparer())).Snapshot(default(ulong)), (default(string) == null ? null : ((ValueComparer<string>)(((IProperty)favouritesIdHash).GetValueComparer())).Snapshot(default(string))), ((ValueComparer<ShikiUserFeatures>)(((IProperty)features).GetValueComparer())).Snapshot(default(ShikiUserFeatures))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<ulong, string, ShikiUserFeatures>(default(ulong), default(string), default(ShikiUserFeatures)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((ShikiUser)(source.Entity));
                    return ((ISnapshot)(new Snapshot<uint, ulong, object, object, object, object>(((ValueComparer<uint>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<uint>(id)), ((ValueComparer<ulong>)(((IProperty)discordUserId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<ulong>(discordUserId)), SnapshotFactoryFactory.SnapshotCollection(ShikiUserUnsafeAccessors.Achievements(entity)), SnapshotFactoryFactory.SnapshotCollection(ShikiUserUnsafeAccessors.Colors(entity)), ShikiUserUnsafeAccessors.DiscordUser(entity), SnapshotFactoryFactory.SnapshotCollection(ShikiUserUnsafeAccessors.Favourites(entity)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 5,
                navigationCount: 4,
                complexPropertyCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 6,
                storeGeneratedCount: 3);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ShikiUsers");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
