<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="AngleSharp" />
        <PackageReference Include="JikanDotNet"/>
        <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\PaperMalKing.MyAnimeList.Wrapper.Abstractions\PaperMalKing.MyAnimeList.Wrapper.Abstractions.csproj" />
      <Compile Remove="Tenrai\ProjectOpenApi.cs" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider.Installer" />
      <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.Wrapper.Tests" />
      <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider.Tests" />
    </ItemGroup>
    
    <PropertyGroup>
        <NoWarn>$(NoWarn);S3242;</NoWarn>
    </PropertyGroup>

</Project>
