<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="DSharpPlus" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="System.Threading.RateLimiting" />
        <PackageReference Include="JikanDotNet"/>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
      <ProjectReference Include="..\PaperMalKing.Database\PaperMalKing.Database.csproj" />
      <ProjectReference Include="..\PaperMalKing.MyAnimeList.UpdateProvider\PaperMalKing.MyAnimeList.UpdateProvider.csproj" />
      <ProjectReference Include="..\PaperMalKing.MyAnimeList.Wrapper.Abstractions\PaperMalKing.MyAnimeList.Wrapper.Abstractions.csproj" />
      <ProjectReference Include="..\PaperMalKing.MyAnimeList.Wrapper\PaperMalKing.MyAnimeList.Wrapper.csproj" />
      <ProjectReference Include="..\PaperMalKing.UpdatesProviders.Base\PaperMalKing.UpdatesProviders.Base.csproj" />
    </ItemGroup>


</Project>
