<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider" />
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider.Installer" />
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider.Tests" />
        <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider" />
        <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider.Installer" />
        <InternalsVisibleTo Include="PaperMalKing.MyAnimeList.UpdateProvider.Tests" />
        <InternalsVisibleTo Include="PaperMalKing.Shikimori.UpdateProvider" />
        <InternalsVisibleTo Include="PaperMalKing.Shikimori.UpdateProvider.Installer" />
        <InternalsVisibleTo Include="PaperMalKing.Shikimori.UpdateProvider.Tests" />
        <InternalsVisibleTo Include="PaperMalKing.UpdatesProviders.Base.Search.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DSharpPlus" />
        <PackageReference Include="DSharpPlus.SlashCommands" />
        <PackageReference Include="Humanizer.Core" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.VisualStudio.Threading" />
        <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" />

        <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
        <ProjectReference Include="..\PaperMalKing.UpdatesProviders.Base\PaperMalKing.UpdatesProviders.Base.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);IDE0290;<!--use primary constructor --></NoWarn>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

</Project>
