<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GraphQL.Client" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" />
        <ProjectReference Include="..\PaperMalKing.AniList.Wrapper.Abstractions\PaperMalKing.AniList.Wrapper.Abstractions.csproj" />
        <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider.Installer" />
    </ItemGroup>

</Project>
