<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <InternalsVisibleTo Include="PaperMalKing.Shikimori.Wrapper.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GraphQL.Client" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" />
        <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
        <ProjectReference Include="..\PaperMalKing.Shikimori.Wrapper.Abstractions\PaperMalKing.Shikimori.Wrapper.Abstractions.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
    
</Project>
