<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\PaperMalKing.Common\PaperMalKing.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider" />
        <InternalsVisibleTo Include="PaperMalKing.AniList.UpdateProvider.Installer" />

    </ItemGroup>

</Project>
